# Generated by Django 2.1.4 on 2019-02-21 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='todolist',
        ),
    ]
