# Generated by Django 2.1.4 on 2019-02-21 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20190221_1218'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='todolist1',
        ),
    ]
