# Generated by Django 2.1.4 on 2019-02-21 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20190221_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='dong',
            new_name='done',
        ),
    ]
